<a href="https://www.kaggle.com/code/vinit0714/exploratory-data-analysis-eda-using-gemma-llm?scriptVersionId=165101046" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os

os.environ["KERAS_BACKEND"] = "torch"  # Or "jax" or "tensorflow".

In [2]:
import keras
import keras_nlp
import numpy as np

2024-03-02 07:51:14.103244: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-02 07:51:14.103415: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-02 07:51:14.320747: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [3]:
gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma_instruct_2b_en")

gemma_lm.generate("Hello, I am", max_length=30)

Attaching 'config.json' from model 'keras/gemma/keras/gemma_instruct_2b_en/2' to your Kaggle notebook...
Attaching 'config.json' from model 'keras/gemma/keras/gemma_instruct_2b_en/2' to your Kaggle notebook...
Attaching 'model.weights.h5' from model 'keras/gemma/keras/gemma_instruct_2b_en/2' to your Kaggle notebook...
Attaching 'tokenizer.json' from model 'keras/gemma/keras/gemma_instruct_2b_en/2' to your Kaggle notebook...
Attaching 'assets/tokenizer/vocabulary.spm' from model 'keras/gemma/keras/gemma_instruct_2b_en/2' to your Kaggle notebook...
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.

'Hello, I am looking for a way to improve my understanding of a specific topic. I have been considering using flashcards, but I am not sure'

In [4]:
prompt = "Exploratory Data Analysis (EDA)"
explanation = gemma_lm.generate(prompt, max_length=400)

print(explanation)

Exploratory Data Analysis (EDA) is a crucial step in data science projects. EDA helps identify patterns, trends, and relationships within the data, leading to better data-driven decisions.

**Here's how EDA can benefit data science projects:**

* **Identify patterns and trends:** EDA helps identify patterns and trends in the data, which can be used to make predictions and insights.
* **Discover relationships between variables:** EDA can help discover relationships between variables, which can lead to the development of new insights and solutions.
* **Clean and prepare data for modeling:** EDA can be used to clean and prepare data for modeling, which can improve the accuracy and performance of machine learning models.
* **Generate insights:** EDA can generate insights and knowledge from the data, which can be used to improve decision-making and problem-solving.

**Here are some common EDA techniques:**

* **Descriptive statistics:** This technique provides summary statistics, such as mean, median, standard deviation, and frequency distribution.
* **Data visualization:** This technique uses visual representations, such as scatter plots, histograms, and box plots, to explore the data and identify patterns.
* **Correlation analysis:** This technique measures the relationship between two variables, and can be used to identify trends and outliers.
* **Anomaly detection:** This technique identifies data points that deviate from the norm, which can be used to identify outliers and potential anomalies.

**Here are some tips for conducting EDA:**

* Start with a clear understanding of the data and the research question.
* Choose the right tools and techniques for the data.
* Use a systematic approach to data exploration.
* Communicate your findings clearly and concisely.

**By following these steps and best practices, you can effectively conduct EDA and gain valuable insights from your data.**

In [5]:
prompt = "Generate example code for performing Exploratory Data Analysis (EDA)."

eda_code = gemma_lm.generate(prompt, max_length=2000)
print(eda_code)

Generate example code for performing Exploratory Data Analysis (EDA).

**Step 1: Load and Explore the Data**

```python
import pandas as pd

# Load the data from a CSV file
data = pd.read_csv("data.csv")

# Print the first 5 rows of the data
print(data.head())

# Explore the data by looking at the data types, column names, and data values
print(data.dtypes)
print(data.columns)
print(data.values)
```

**Step 2: Data Cleaning and Preprocessing**

```python
# Drop rows with missing values
data.dropna(inplace=True, subset="index")

# Convert categorical variables to numerical variables
data["category_column"] = data["category_column"].astype(int)

# Normalize numerical variables
data["numerical_column"] = (data["numerical_column"] - mean(data["numerical_column"])) / standard_deviation(data["numerical_column"])
```

**Step 3: Descriptive Statistics and Data Visualization**

```python
# Calculate descriptive statistics for numerical variables
print(data.describe())

# Create a histogram of a numerical variable
plt.hist(data["numerical_column"])
plt.title("Histogram of Numerical Variable")
plt.show()

# Create a box plot of a numerical variable
plt.boxplot(data["numerical_column"])
plt.title("Boxplot of Numerical Variable")
plt.show()

# Create a scatter plot between two numerical variables
plt.scatter(data["numerical_column1"], data["numerical_column2"])
plt.title("Scatterplot of Numerical Variables")
plt.show()
```

**Step 4: Identify Patterns and Relationships**

```python
# Group the data by a categorical variable and calculate the mean of a numerical variable
data.groupby("category_column")["numerical_column"].mean()

# Find correlations between numerical variables
data.corr()
```

**Step 5: Report and Share the Findings**

```python
# Create a report on the data
print(data.to_string())

# Save the report to a file
data.to_csv("eda_report.csv", index=False)

# Share the report with others
print("EDA Report Generated!")
```

In [6]:
import pandas as pd

In [7]:
data = pd.read_csv("/kaggle/input/fast-food-sales-report/Balaji Fast Food Sales.csv")

In [8]:
data.head(5)

,order_id,date,item_name,item_type,item_price,quantity,transaction_amount,transaction_type,received_by,time_of_sale
0,1,07-03-2022,Aalopuri,Fastfood,20,13,260,NaN,Mr.,Night
1,2,8/23/2022,Vadapav,Fastfood,20,15,300,Cash,Mr.,Afternoon
2,3,11/20/2022,Vadapav,Fastfood,20,1,20,Cash,Mr.,Afternoon
3,4,02-03-2023,Sugarcane juice,Beverages,25,6,150,Online,Mr.,Night
4,5,10-02-2022,Sugarcane juice,Beverages,25,8,200,Online,Mr.,Evening

In [9]:
print(data.dtypes)

order_id               int64
date                  object
item_name             object
item_type             object
item_price             int64
quantity               int64
transaction_amount     int64
transaction_type      object
received_by           object
time_of_sale          object
dtype: object

In [10]:
print(data.columns)

Index(['order_id', 'date', 'item_name', 'item_type', 'item_price', 'quantity',
       'transaction_amount', 'transaction_type', 'received_by',
       'time_of_sale'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            1000 non-null   int64
 1   date                1000 non-null   object
 2   item_name           1000 non-null   object
 3   item_type           1000 non-null   object
 4   item_price          1000 non-null   int64
 5   quantity            1000 non-null   int64
 6   transaction_amount  1000 non-null   int64
 7   transaction_type    893 non-null    object
 8   received_by         1000 non-null   object
 9   time_of_sale        1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.2+ KB

In [12]:
print(data.values)

[[1 '07-03-2022' 'Aalopuri' ... nan 'Mr.' 'Night']
 [2 '8/23/2022' 'Vadapav' ... 'Cash' 'Mr.' 'Afternoon']
 [3 '11/20/2022' 'Vadapav' ... 'Cash' 'Mr.' 'Afternoon']
 ...
 [998 '1/26/2023' 'Sandwich' ... nan 'Mr.' 'Evening']
 [999 '8/27/2022' 'Panipuri' ... nan 'Mrs.' 'Afternoon']
 [1000 '5/29/2022' 'Aalopuri' ... 'Online' 'Mrs.' 'Midnight']]

In [13]:
prompt = """I am working on a python notebook and in my dataset date column i have some dataset different format like 07-03-2022 and 8/23/2022.
I want to replace / with - in my date dataset and so convert all dataset to format like 07-03-2022"""

solve_problem = gemma_lm.generate(prompt, max_length=500)
print(solve_problem)

I am working on a python notebook and in my dataset date column i have some dataset different format like 07-03-2022 and 8/23/2022.
I want to replace / with - in my date dataset and so convert all dataset to format like 07-03-2022.

Here is my code:

```python
import pandas as pd

# Load the dataset
df = pd.read_csv("your_file.csv")

# Replace / with - in the date column
df["date"] = df["date"].str.replace("/", "-")

# Convert the date column to the desired format
df["date"] = pd.to_datetime(df["date"], format="%d-%m-%Y")

# Print the resulting dataframe
print(df)
```

**Output:**

```
           date
0  07-03-2022
1  08-23-2022
```

**Explanation:**

1. `str.replace("/", "-")` replaces all occurrences of `/` with `-` in the `date` column.
2. `pd.to_datetime()` converts the `date` column to a datetime object, with the format `"%d-%m-%Y"`. This format is recognized by pandas as the date and time in that order.

**Note:**

* Ensure that the date format in your dataset is consistent throughout the column.
* You can adjust the date format in the `format` parameter of `pd.to_datetime()` to suit your needs.

In [14]:
data['date'].str.replace('/', '-')
data['date']=pd.to_datetime(data['date'],format="mixed")
data.head()

,order_id,date,item_name,item_type,item_price,quantity,transaction_amount,transaction_type,received_by,time_of_sale
0,1,2022-07-03,Aalopuri,Fastfood,20,13,260,NaN,Mr.,Night
1,2,2022-08-23,Vadapav,Fastfood,20,15,300,Cash,Mr.,Afternoon
2,3,2022-11-20,Vadapav,Fastfood,20,1,20,Cash,Mr.,Afternoon
3,4,2023-02-03,Sugarcane juice,Beverages,25,6,150,Online,Mr.,Night
4,5,2022-10-02,Sugarcane juice,Beverages,25,8,200,Online,Mr.,Evening

In [15]:
data.isna().sum()

order_id                0
date                    0
item_name               0
item_type               0
item_price              0
quantity                0
transaction_amount      0
transaction_type      107
received_by             0
time_of_sale            0
dtype: int64

In [16]:
data.dropna(inplace=True)

In [17]:
data.shape

(893, 10)

In [18]:
data

,order_id,date,item_name,item_type,item_price,quantity,transaction_amount,transaction_type,received_by,time_of_sale
1,2,2022-08-23,Vadapav,Fastfood,20,15,300,Cash,Mr.,Afternoon
2,3,2022-11-20,Vadapav,Fastfood,20,1,20,Cash,Mr.,Afternoon
3,4,2023-02-03,Sugarcane juice,Beverages,25,6,150,Online,Mr.,Night
4,5,2022-10-02,Sugarcane juice,Beverages,25,8,200,Online,Mr.,Evening
5,6,2022-11-14,Vadapav,Fastfood,20,10,200,Cash,Mr.,Evening
...,...,...,...,...,...,...,...,...,...,...
991,992,2022-10-21,Sandwich,Fastfood,60,5,300,Cash,Mr.,Morning
992,993,2022-07-17,Frankie,Fastfood,50,3,150,Online,Mrs.,Night
993,994,2022-11-01,Panipuri,Fastfood,20,2,40,Online,Mrs.,Evening
994,995,2022-06-18,Sugarcane juice,Beverages,25,1,25,Online,Mr.,Night
999,1000,2022-05-29,Aalopuri,Fastfood,20,3,60,Online,Mrs.,Midnight

In [19]:
data['item_type'].nunique()

2

In [20]:
data['item_name'].nunique()

7

In [21]:
data['transaction_type'].nunique()

2

In [22]:
data['time_of_sale'].nunique()

5

In [23]:
data["item_type"] = data["item_type"].astype('category').cat.codes
data["item_name"] = data["item_name"].astype('category').cat.codes
data["transaction_type"] = data["transaction_type"].astype('category').cat.codes
data["time_of_sale"] = data["time_of_sale"].astype('category').cat.codes

In [24]:
data.dtypes

order_id                       int64
date                  datetime64[ns]
item_name                       int8
item_type                       int8
item_price                     int64
quantity                       int64
transaction_amount             int64
transaction_type                int8
received_by                   object
time_of_sale                    int8
dtype: object

In [25]:
prompt = """I have fast food sales dataset with columns and dataset as follows:
order_id                       int64
date                  datetime64[ns]
item_name                       int8
item_type                       int8
item_price                     int64
quantity                       int64
transaction_amount             int64
transaction_type                int8
received_by                   object
time_of_sale                    int8

so on what factors from above dataset my EDA should be performed?? Explain the reasoning behind selection of those factors"""

solve_problem = gemma_lm.generate(prompt, max_length=2000)
print(solve_problem)

I have fast food sales dataset with columns and dataset as follows:
order_id                       int64
date                  datetime64[ns]
item_name                       int8
item_type                       int8
item_price                     int64
quantity                       int64
transaction_amount             int64
transaction_type                int8
received_by                   object
time_of_sale                    int8

so on what factors from above dataset my EDA should be performed?? Explain the reasoning behind selection of those factors.

**Factors to consider for EDA:**

* **Time series analysis:** Examine trends, seasonality, and cyclical patterns in order_id, date, item_name, item_price, and transaction_amount.
* **Cross-tabulation:** Analyze relationships between item_name, item_type, transaction_type, and received_by.
* **Distribution analysis:** Explore the distribution of numerical and categorical variables.
* **Relationship analysis:** Identify correlations between variables, such as item_price and transaction_amount.
* **Outlier analysis:** Identify and analyze extreme values or outliers in the data.

**Rationale for selection:**

* **Time series analysis:** Time series analysis is crucial for understanding order patterns, peak hours, and seasonal trends.
* **Cross-tabulation:** Cross-tabulation helps identify item combinations, purchase patterns, and potential relationships between items.
* **Distribution analysis:** Distribution analysis provides insights into the distribution of prices, quantities, and transaction amounts.
* **Relationship analysis:** Identifying correlations between variables helps identify factors that influence each other.
* **Outlier analysis:** Outlier analysis identifies unusual observations that may indicate data errors or unusual purchase patterns.

**Additional considerations:**

* **Data cleaning:** Before performing EDA, data cleaning and normalization may be necessary to ensure data quality and consistency.
* **Data transformation:** Consider transforming variables, such as transaction_amount, to make them suitable for analysis.
* **Visualization:** Create visual representations, such as charts and graphs, to explore patterns and relationships in the data.